### Post Route

GET http://localhost:3000/post/all 
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
###

GET http://localhost:3000/post/allByUser/65aba6e2ee855cb9ccc1288f
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYTZlMmVlODU1Y2I5Y2NjMTI4OGYiLCJpYXQiOjE3MDU3NDgyNTV9.hQRSZcmF5d7nZlbzWgRE6n5PcxUKrA-setKxlOneVYo
###

GET http://localhost:3000/post/feed
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYTZlMmVlODU1Y2I5Y2NjMTI4OGYiLCJpYXQiOjE3MDU3NDgyNTV9.hQRSZcmF5d7nZlbzWgRE6n5PcxUKrA-setKxlOneVYo
###

POST http://localhost:3000/post/create
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFiYTZlMmVlODU1Y2I5Y2NjMTI4OGYiLCJpYXQiOjE3MDU3NDgyNTV9.hQRSZcmF5d7nZlbzWgRE6n5PcxUKrA-setKxlOneVYo
Content-Type: application/json

{
    "breedId": 5,
    "breed": "Pomeranian",
    "description": "Tiny female, 6 years old",
    "image": ""
}

###

POST  http://localhost:3000/post/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "postId": "65aa9e99c1f558fdf93df4a4",
    "text": "Such a cool dog!"
}

###

PUT  http://localhost:3000/post/edit
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "_id": "65aa9e99c1f558fdf93df4a4",
    "breedId": 100,
    "breed": "Labrador",
    "description": "Known for its intelligence and versatility, Labradors are often cherished as family pets."
}

###

PUT  http://localhost:3000/post/dislike
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "_id": "65aa9e99c1f558fdf93df4a4"
}

###

PUT  http://localhost:3000/post/like
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "_id": "65aa9e99c1f558fdf93df4a4"
}

###

DELETE  http://localhost:3000/post/delete
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "_id": "65aa9e99c1f558fdf93df4a4"
}

###

GET  http://localhost:3000/post/comments/65aa9e99c1f558fdf93df4a4
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ


### User Route

GET http://localhost:3000/user/details/65aabfbdc5425b74b6d0e975
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ

###

PUT http://localhost:3000/user/edit
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE3ZjNiMDI1NWMwNjZhN2JjNWQ1YjAiLCJpYXQiOjE3MDU1MDU3MzN9.LP_M6Q623yBFIr53Dr7So9lz9oFHb2SNlUcG1xizPxQ
Content-Type: application/json

{
    "_id": "65aabfbdc5425b74b6d0e975",
    "firstname": "Amit"
}

### Auth Route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "orip",
    "password": "1234567890",
    "firstname": "ori",
    "lastname": "levi",
    "userImage": " ",
    "description": " ",
    "phoneNumber": "050-0000000"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "orip",
    "password": "1234567890"
}