###

GET http://localhost:3000/user
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk5ODdhYzY1M2RmZmE1YmFjM2Q3ODUiLCJpYXQiOjE3MDQ1NjE2NjV9.2DAqv2YYA3whtxvWcVftSFb3scy4yzaRROW6oe-WERM
###

GET http://localhost:3000/user?username=alonl


###

GET http://localhost:3000/auth/1234567891


###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "alonl",
    "password": "1234567890",
    "firstname": "alon",
    "lastname": "levi",
    "phoneNumber": "050-0000000"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "alonl",
    "password": "1234567890"
}