import post_dog_img from "../../../public/images/post_dog_img.jpg";

export const postsData = [
  {
    id: 1,
    ownerId: 101,
    ownerUsername: "doglover1",
    img: post_dog_img,
    description: "Meet my adorable Labrador! 🐾",
    isLikedByUser: true,
    numOfLikes: 152,
    numOfComments: 20,
    breed: "Labrador Retriever",
    createdAt: "2022-01-01T00:00:00.000Z",
  },
  {
    id: 2,
    ownerId: 102,
    ownerUsername: "pawsandwhiskers",
    img: post_dog_img,
    description: "Just adopted this little cutie! ❤️ #RescueDog",
    isLikedByUser: false,
    numOfLikes: 98,
    numOfComments: 15,
    breed: "Mixed Breed",
    createdAt: "2022-01-02T00:00:00.000Z",
  },
  {
    id: 3,
    ownerId: 103,
    ownerUsername: "happyhounds",
    img: post_dog_img,
    description: "Morning walk with my fluffy friend! 🌞 #PomeranianLove",
    isLikedByUser: true,
    numOfLikes: 120,
    numOfComments: 18,
    breed: "Pomeranian",
    createdAt: "2022-01-03T00:00:00.000Z",
  },
  {
    id: 4,
    ownerId: 104,
    ownerUsername: "terrierfanatic",
    img: post_dog_img,
    description: "Terrier mischief in the backyard! 🏡 #TerrierLife",
    isLikedByUser: false,
    numOfLikes: 64,
    numOfComments: 10,
    breed: "Terrier",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 5,
    ownerId: 105,
    ownerUsername: "bullybuddies",
    img: post_dog_img,
    description: "Bulldog cuddles are the best! 🤗 #EnglishBulldog",
    isLikedByUser: true,
    numOfLikes: 180,
    numOfComments: 25,
    breed: "English Bulldog",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 6,
    ownerId: 106,
    ownerUsername: "greyhoundgalore",
    img: post_dog_img,
    description: "Speedy Greyhound on the track! 🏁 #GreyhoundLove",
    isLikedByUser: false,
    numOfLikes: 45,
    numOfComments: 8,
    breed: "Greyhound",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 7,
    ownerId: 107,
    ownerUsername: "dachshunddelight",
    img: post_dog_img,
    description: "Dachshund adventures in the park! 🌳 #WienerDog",
    isLikedByUser: true,
    numOfLikes: 112,
    numOfComments: 15,
    breed: "Dachshund",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 8,
    ownerId: 108,
    ownerUsername: "huskyheaven",
    img: post_dog_img,
    description: "Siberian Husky enjoying the snow! ❄️ #HuskyLife",
    isLikedByUser: false,
    numOfLikes: 78,
    numOfComments: 12,
    breed: "Siberian Husky",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 9,
    ownerId: 109,
    ownerUsername: "beaglebliss",
    img: post_dog_img,
    description: "Beagle sniffing around the garden! 🌺 #BeagleLove",
    isLikedByUser: true,
    numOfLikes: 95,
    numOfComments: 14,
    breed: "Beagle",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 10,
    ownerId: 110,
    ownerUsername: "goldenmoments",
    img: post_dog_img,
    description: "Golden Retriever sunset stroll! 🌅 #GoldenRetriever",
    isLikedByUser: false,
    numOfLikes: 120,
    numOfComments: 18,
    breed: "Golden Retriever",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 11,
    ownerId: 111,
    ownerUsername: "boxerbuddies",
    img: post_dog_img,
    description: "Playtime with my energetic Boxer! 🥊 #BoxerLove",
    isLikedByUser: true,
    numOfLikes: 150,
    numOfComments: 22,
    breed: "Boxer",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 12,
    ownerId: 112,
    ownerUsername: "corgicraze",
    img: post_dog_img,
    description: "Corgi cuteness overload! 🍑 #CorgiLife",
    isLikedByUser: false,
    numOfLikes: 88,
    numOfComments: 16,
    breed: "Pembroke Welsh Corgi",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 13,
    ownerId: 113,
    ownerUsername: "greatdanefans",
    img: post_dog_img,
    description: "Gentle giant enjoying the backyard! 🏡 #GreatDane",
    isLikedByUser: true,
    numOfLikes: 105,
    numOfComments: 20,
    breed: "Great Dane",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 14,
    ownerId: 114,
    ownerUsername: "shibainuantics",
    img: post_dog_img,
    description: "Shiba Inu doing tricks for treats! 🎾 #ShibaInu",
    isLikedByUser: false,
    numOfLikes: 72,
    numOfComments: 14,
    breed: "Shiba Inu",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 15,
    ownerId: 115,
    ownerUsername: "rottweilerroyalty",
    img: post_dog_img,
    description: "Rottweiler posing for the camera! 📸 #Rottweiler",
    isLikedByUser: true,
    numOfLikes: 135,
    numOfComments: 25,
    breed: "Rottweiler",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 16,
    ownerId: 116,
    ownerUsername: "maltesemagic",
    img: post_dog_img,
    description: "Maltese enjoying a sunny day! ☀️ #Maltese",
    isLikedByUser: false,
    numOfLikes: 58,
    numOfComments: 10,
    breed: "Maltese",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 17,
    ownerId: 117,
    ownerUsername: "poodleperfection",
    img: post_dog_img,
    description: "Fancy Poodle showing off! 🎀 #Poodle",
    isLikedByUser: true,
    numOfLikes: 92,
    numOfComments: 15,
    breed: "Poodle",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 18,
    ownerId: 118,
    ownerUsername: "bordercolliecharm",
    img: post_dog_img,
    description: "Border Collie herding skills! 🐑 #BorderCollie",
    isLikedByUser: false,
    numOfLikes: 110,
    numOfComments: 20,
    breed: "Border Collie",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 19,
    ownerId: 119,
    ownerUsername: "cockerspanielcuddles",
    img: post_dog_img,
    description: "Cocker Spaniel nap time! 😴 #CockerSpaniel",
    isLikedByUser: true,
    numOfLikes: 80,
    numOfComments: 12,
    breed: "Cocker Spaniel",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
  {
    id: 20,
    ownerId: 120,
    ownerUsername: "aussieadventures",
    img: post_dog_img,
    description: "Australian Shepherd agility training! 🏃 #AustralianShepherd",
    isLikedByUser: false,
    numOfLikes: 94,
    numOfComments: 18,
    breed: "Australian Shepherd",
    createdAt: "2022-01-04T00:00:00.000Z",
  },
];
